spring:
  application:
    name: r-pan-server
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 3072MB
      max-request-size: 3072MB
  datasource:
    username: root
    password: 101807
    url: jdbc:mysql://localhost:3306/m_pan?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: env,beans

swagger2:
  enable: true

mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml


#pan:
#  storage:
#    engine:
#      fastdfs:
#        tracker-list:
#          - 119.45.54.2:22122
#        connect-timeout: 10000
#pan:
#  storage:
#    engine:
#      oss:
#        endpoint: oss-cn-chengdu.aliyuncs.com
#        bucket-name: pandaer-dev-01
#        access-key-id:
#        access-key-secret:
#        auto-create-bucket: true
pan:
  server:
    share-prefix: http://127.0.0.1:5173
  bloom:
    filter:
      local:
        items:
          - name: SHARE_SIMPLE_BLOOM_FILTER
            funnel-type-name: LONG
            expected-insertions: 100000
            fpp: 0.01

